Repository prgrms-web-devcourse/Team-MusseukPeople-WooriMap-BE, pull requests merged in 2022-07, with the labels that each got.

#2 [WOOR-67] Swaager 설정
  config/infra/docker-compose.yml
  src/main/java/com/musseukpeople/woorimap/HealthCheckController.java
  src/main/java/com/musseukpeople/woorimap/common/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: 🔨 chore

#4 [WOOR-77] ApiResponse 구현
  src/main/java/com/musseukpeople/woorimap/common/model/ApiResponse.java
Labels: 백엔드, 🎵 feat

#5 [WOOR-78] QueryDsl 설정
  src/main/java/com/musseukpeople/woorimap/common/config/QueryDslConfig.java
Labels: 백엔드, 🔨 chore

#6 [WOOR-79] feat: Exception 구현
  src/main/java/com/musseukpeople/woorimap/common/exception/BusinessException.java
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorResponse.java
  src/main/java/com/musseukpeople/woorimap/common/exception/GlobalExceptionHandler.java
Labels: 백엔드, 🎵 feat

#7 [WOOR-47] feat: 회원가입 API 구현
  build.gradle
  src/main/java/com/musseukpeople/woorimap/HealthCheckController.java
  src/main/java/com/musseukpeople/woorimap/WoorimapApplication.java
  src/main/java/com/musseukpeople/woorimap/common/config/PasswordEncoderConfig.java
  src/main/java/com/musseukpeople/woorimap/common/config/QueryDslConfig.java
  src/main/java/com/musseukpeople/woorimap/common/config/SwaggerConfig.java
  src/main/java/com/musseukpeople/woorimap/common/exception/BusinessException.java
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorResponse.java
  src/main/java/com/musseukpeople/woorimap/common/exception/GlobalExceptionHandler.java
  src/main/java/com/musseukpeople/woorimap/common/model/ApiResponse.java
  src/main/java/com/musseukpeople/woorimap/member/application/MemberService.java
  src/main/java/com/musseukpeople/woorimap/member/application/dto/request/SignupRequest.java
  src/main/java/com/musseukpeople/woorimap/member/domain/Member.java
  src/main/java/com/musseukpeople/woorimap/member/domain/MemberRepository.java
  src/main/java/com/musseukpeople/woorimap/member/domain/vo/Email.java
  src/main/java/com/musseukpeople/woorimap/member/domain/vo/NickName.java
  src/main/java/com/musseukpeople/woorimap/member/domain/vo/Password.java
  src/main/java/com/musseukpeople/woorimap/member/exception/DuplicateEmailException.java
  src/main/java/com/musseukpeople/woorimap/member/exception/LoginFailedException.java
  src/main/java/com/musseukpeople/woorimap/member/exception/MemberException.java
  src/main/java/com/musseukpeople/woorimap/member/presentation/MemberController.java
  src/main/resources/application-test.yml
  src/main/resources/logback-spring.xml
  src/test/java/com/musseukpeople/woorimap/WoorimapApplicationTests.java
  src/test/java/com/musseukpeople/woorimap/member/acceptance/MemberAcceptanceTest.java
  src/test/java/com/musseukpeople/woorimap/member/application/MemberServiceTest.java
  src/test/java/com/musseukpeople/woorimap/member/domain/MemberTest.java
  src/test/java/com/musseukpeople/woorimap/member/domain/vo/EmailTest.java
  src/test/java/com/musseukpeople/woorimap/member/domain/vo/NickNameTest.java
  src/test/java/com/musseukpeople/woorimap/member/domain/vo/PasswordTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
  src/test/java/com/musseukpeople/woorimap/util/DatabaseCleanup.java
Labels: 🎵 feat

#8 [WOOR-80] feat: 커플 엔티티 생성
  src/main/java/com/musseukpeople/woorimap/couple/domain/Couple.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/CoupleRepository.java
  src/test/java/com/musseukpeople/woorimap/couple/domain/CoupleTest.java
Labels: 백엔드, 🎵 feat

#9 [WOOR-53] feat: 로그인 API 구현
  .gitignore
  build.gradle
  src/main/java/com/musseukpeople/woorimap/auth/application/AuthService.java
  src/main/java/com/musseukpeople/woorimap/auth/application/JwtProvider.java
  src/main/java/com/musseukpeople/woorimap/auth/application/TokenService.java
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/request/SignInRequest.java
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/response/MemberResponse.java
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/response/TokenResponse.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/Token.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/TokenRepository.java
  src/main/java/com/musseukpeople/woorimap/auth/exception/InvalidTokenException.java
  src/main/java/com/musseukpeople/woorimap/auth/infrastructure/JwtTokenProvider.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthController.java
  src/main/java/com/musseukpeople/woorimap/common/config/PasswordEncoderConfig.java
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/common/model/ApiResponse.java
  src/main/java/com/musseukpeople/woorimap/member/application/MemberService.java
  src/main/java/com/musseukpeople/woorimap/member/domain/Member.java
  src/main/java/com/musseukpeople/woorimap/member/domain/MemberRepository.java
  src/main/java/com/musseukpeople/woorimap/member/exception/NotFoundMemberException.java
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/musseukpeople/woorimap/auth/application/AuthServiceTest.java
  src/test/java/com/musseukpeople/woorimap/auth/infrastructure/JwtTokenProviderTest.java
  src/test/java/com/musseukpeople/woorimap/auth/presentation/AuthControllerTest.java
  src/test/java/com/musseukpeople/woorimap/member/acceptance/MemberAcceptanceTest.java
  src/test/java/com/musseukpeople/woorimap/member/application/MemberServiceTest.java
  src/test/java/com/musseukpeople/woorimap/member/domain/MemberTest.java
  src/test/java/com/musseukpeople/woorimap/member/domain/vo/EmailTest.java
  src/test/java/com/musseukpeople/woorimap/member/domain/vo/NickNameTest.java
  src/test/java/com/musseukpeople/woorimap/member/domain/vo/PasswordTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
  src/test/java/com/musseukpeople/woorimap/util/fixture/TMemberBuilder.java
Labels: 🎵 feat

#13 [WOOR-111] chore: 로그백 & 도커 로그 볼륨 설정 추가
  Dockerfile-dev
  Dockerfile-prod
  src/main/java/com/musseukpeople/woorimap/HealthCheckController.java
  src/main/resources/logback-spring.xml
Labels: 🔨 chore

#12 [WOOR-95] chore: CORS 설정
  src/main/java/com/musseukpeople/woorimap/common/config/WebConfig.java
Labels: 🔨 chore

#14 [WOOR-54] feat: 로그인 인증 기능 구현
  src/main/java/com/musseukpeople/woorimap/auth/application/AuthService.java
  src/main/java/com/musseukpeople/woorimap/auth/application/JwtProvider.java
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/response/LoginMemberResponse.java
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/response/TokenResponse.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/login/Login.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/login/LoginMember.java
  src/main/java/com/musseukpeople/woorimap/auth/exception/UnauthorizedException.java
  src/main/java/com/musseukpeople/woorimap/auth/infrastructure/AuthorizationExtractor.java
  src/main/java/com/musseukpeople/woorimap/auth/infrastructure/JwtTokenProvider.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthArgumentResolver.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthInterceptor.java
  src/main/java/com/musseukpeople/woorimap/common/config/WebConfig.java
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/test/java/com/musseukpeople/woorimap/auth/infrastructure/AuthorizationExtractorTest.java
  src/test/java/com/musseukpeople/woorimap/auth/presentation/AuthArgumentResolverTest.java
  src/test/java/com/musseukpeople/woorimap/auth/presentation/AuthInterceptorTest.java
Labels: 🎵 feat

#15 [WOOR-32] feat: 로그아웃 API 구현
  src/main/java/com/musseukpeople/woorimap/auth/application/AuthService.java
  src/main/java/com/musseukpeople/woorimap/auth/application/TokenService.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/TokenRepository.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthController.java
  src/test/java/com/musseukpeople/woorimap/auth/application/AuthServiceTest.java
  src/test/java/com/musseukpeople/woorimap/auth/presentation/AuthControllerTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
Labels: 🎵 feat

#17 [WOOR-33] feat: 회원 탈퇴 API 구현
  src/main/java/com/musseukpeople/woorimap/auth/domain/login/Login.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthInterceptor.java
  src/main/java/com/musseukpeople/woorimap/common/config/SwaggerConfig.java
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/member/application/MemberService.java
  src/main/java/com/musseukpeople/woorimap/member/presentation/MemberController.java
  src/test/java/com/musseukpeople/woorimap/auth/acceptance/AuthControllerTest.java
  src/test/java/com/musseukpeople/woorimap/member/acceptance/MemberAcceptanceTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
Labels: 🎵 feat
