Repository prgrms-web-devcourse/Team-MusseukPeople-WooriMap-BE, pull requests merged in 2022-08, with the labels that each got.

#19 [WOOR-118] feat: 토큰 재발급 API 구현
  src/main/java/com/musseukpeople/woorimap/auth/application/AuthService.java
  src/main/java/com/musseukpeople/woorimap/auth/application/TokenService.java
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/request/RefreshTokenRequest.java
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/response/AccessTokenResponse.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/Token.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/TokenRepository.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthController.java
  src/main/java/com/musseukpeople/woorimap/common/config/WebConfig.java
  src/test/java/com/musseukpeople/woorimap/auth/acceptance/AuthControllerTest.java
  src/test/java/com/musseukpeople/woorimap/auth/application/AuthServiceTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
Labels: 🎵 feat

#16 [WOOR-34] feat: 초대 코드 생성 API 구현
  src/main/java/com/musseukpeople/woorimap/couple/application/CodeGenerator.java
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleFacade.java
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleService.java
  src/main/java/com/musseukpeople/woorimap/couple/application/InviteCodeService.java
  src/main/java/com/musseukpeople/woorimap/couple/application/dto/response/InviteCodeResponse.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/Couple.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/InviteCode.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/InviteCodeRepository.java
  src/main/java/com/musseukpeople/woorimap/couple/infrastructure/InviteCodQueryRepository.java
  src/main/java/com/musseukpeople/woorimap/couple/infrastructure/InviteCodQueryRepositoryImpl.java
  src/main/java/com/musseukpeople/woorimap/couple/infrastructure/RandomCodeGenerator.java
  src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
  src/test/java/com/musseukpeople/woorimap/couple/application/InviteCodeServiceTest.java
  src/test/java/com/musseukpeople/woorimap/couple/domain/CoupleTest.java
  src/test/java/com/musseukpeople/woorimap/couple/domain/InviteCodeTest.java
  src/test/java/com/musseukpeople/woorimap/couple/infrastructure/InviteCodQueryRepositoryTest.java
  src/test/java/com/musseukpeople/woorimap/couple/presentation/CoupleControllerTest.java
  src/test/java/com/musseukpeople/woorimap/util/DatabaseCleanup.java
  src/test/java/com/musseukpeople/woorimap/util/QueryDslTestConfig.java
  src/test/java/com/musseukpeople/woorimap/util/RepositoryTest.java
Labels: 백엔드, 🎵 feat

#20 [WOOR-130] feat: BaseEntity 생성
  src/main/java/com/musseukpeople/woorimap/common/config/JpaAuditingConfig.java
  src/main/java/com/musseukpeople/woorimap/common/model/BaseEntity.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/Couple.java
Labels: 백엔드, 🎵 feat

#22 [WOOR-132] refactor: refreshToken 쿠키로 보내도록 변경
  src/main/java/com/musseukpeople/woorimap/auth/application/AuthService.java
  src/main/java/com/musseukpeople/woorimap/auth/application/JwtProvider.java
  src/main/java/com/musseukpeople/woorimap/auth/application/TokenService.java
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/TokenDto.java
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/request/RefreshTokenRequest.java
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/response/LoginMemberResponse.java
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/response/LoginResponseDto.java
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/response/TokenResponse.java
  src/main/java/com/musseukpeople/woorimap/auth/infrastructure/JwtTokenProvider.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthController.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/dto/response/LoginResponse.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/resolver/AuthArgumentResolver.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/resolver/JwtToken.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/resolver/JwtTokenArgumentResolver.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/resolver/RequestTokens.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/util/CookieUtil.java
  src/main/java/com/musseukpeople/woorimap/common/config/WebConfig.java
  src/test/java/com/musseukpeople/woorimap/auth/acceptance/AuthControllerTest.java
  src/test/java/com/musseukpeople/woorimap/auth/application/AuthServiceTest.java
  src/test/java/com/musseukpeople/woorimap/auth/infrastructure/JwtTokenProviderTest.java
  src/test/java/com/musseukpeople/woorimap/auth/presentation/AuthInterceptorTest.java
  src/test/java/com/musseukpeople/woorimap/auth/presentation/resolver/AuthArgumentResolverTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
Labels: 🍰 refactor

#24 [WOOR-69] feat: 커플 해제 API 구현
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleFacade.java
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleService.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/Couple.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/CoupleRepository.java
  src/main/java/com/musseukpeople/woorimap/couple/exception/CoupleException.java
  src/main/java/com/musseukpeople/woorimap/couple/exception/NotFoundCoupleException.java
  src/main/java/com/musseukpeople/woorimap/couple/infrastructure/CoupleQueryRepository.java
  src/main/java/com/musseukpeople/woorimap/couple/infrastructure/CoupleQueryRepositoryImpl.java
  src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
  src/main/java/com/musseukpeople/woorimap/member/application/MemberService.java
  src/main/java/com/musseukpeople/woorimap/member/domain/MemberRepository.java
  src/test/java/com/musseukpeople/woorimap/couple/application/CoupleServiceTest.java
  src/test/java/com/musseukpeople/woorimap/couple/application/InviteCodeServiceTest.java
  src/test/java/com/musseukpeople/woorimap/couple/presentation/CoupleControllerTest.java
Labels: 백엔드, 🎵 feat

#25 [WOOR-142] feat: 테스트 로그인용 API 구현
  src/main/java/com/musseukpeople/woorimap/auth/presentation/fake/FakeAuthController.java
  src/main/java/com/musseukpeople/woorimap/common/config/WebConfig.java
Labels: 🎵 feat

#26 [WOOR-141] feat: 인가 기능 구현
  src/main/java/com/musseukpeople/woorimap/auth/aop/LoginMemberVerifier.java
  src/main/java/com/musseukpeople/woorimap/auth/aop/LoginRequired.java
  src/main/java/com/musseukpeople/woorimap/auth/aop/MemberAuthorityContext.java
  src/main/java/com/musseukpeople/woorimap/auth/aop/OnlyCouple.java
  src/main/java/com/musseukpeople/woorimap/auth/aop/OnlySolo.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/login/LoginMember.java
  src/main/java/com/musseukpeople/woorimap/auth/exception/MemberAccessDeniedExcpetion.java
  src/main/java/com/musseukpeople/woorimap/auth/infrastructure/AuthorizationExtractor.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthController.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthInterceptor.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/resolver/AuthArgumentResolver.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/resolver/JwtTokenArgumentResolver.java
  src/main/java/com/musseukpeople/woorimap/common/config/SwaggerConfig.java
  src/main/java/com/musseukpeople/woorimap/common/config/WebConfig.java
  src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
  src/main/java/com/musseukpeople/woorimap/member/domain/MemberRepository.java
  src/main/java/com/musseukpeople/woorimap/member/presentation/MemberController.java
  src/test/java/com/musseukpeople/woorimap/auth/infrastructure/AuthorizationExtractorTest.java
  src/test/java/com/musseukpeople/woorimap/auth/presentation/AuthInterceptorTest.java
  src/test/java/com/musseukpeople/woorimap/auth/presentation/resolver/AuthArgumentResolverTest.java
  src/test/java/com/musseukpeople/woorimap/couple/presentation/CoupleControllerTest.java
Labels: 🎵 feat, 🍰 refactor

#27 [ WOOR-145] fix : cors origin 및 credentials 설정
  src/main/java/com/musseukpeople/woorimap/auth/infrastructure/JwtTokenProvider.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/fake/FakeAuthController.java
  src/main/java/com/musseukpeople/woorimap/common/config/WebConfig.java
Labels: 🐛 bug

#29 [WOOR-149] chore: https 적용
  src/main/resources/application.yml
Labels: 🔨 chore

#28 [WOOR-70] feat: 커플 맺기 API 구현
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleFacade.java
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleService.java
  src/main/java/com/musseukpeople/woorimap/couple/application/InviteCodeService.java
  src/main/java/com/musseukpeople/woorimap/couple/application/dto/request/CreateCoupleRequest.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/Couple.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/vo/CoupleMembers.java
  src/main/java/com/musseukpeople/woorimap/couple/exception/AlreadyCoupleException.java
  src/main/java/com/musseukpeople/woorimap/couple/exception/CreateCoupleFailException.java
  src/main/java/com/musseukpeople/woorimap/couple/exception/NotFoundCoupleException.java
  src/main/java/com/musseukpeople/woorimap/couple/exception/NotFoundInviteCodeException.java
  src/main/java/com/musseukpeople/woorimap/couple/infrastructure/InviteCodQueryRepository.java
  src/main/java/com/musseukpeople/woorimap/couple/infrastructure/InviteCodQueryRepositoryImpl.java
  src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
  src/test/java/com/musseukpeople/woorimap/couple/application/CoupleServiceTest.java
  src/test/java/com/musseukpeople/woorimap/couple/application/InviteCodeServiceTest.java
  src/test/java/com/musseukpeople/woorimap/couple/domain/CoupleTest.java
  src/test/java/com/musseukpeople/woorimap/couple/domain/vo/CoupleMembersTest.java
  src/test/java/com/musseukpeople/woorimap/couple/presentation/CoupleControllerTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
  src/test/java/com/musseukpeople/woorimap/util/fixture/TCoupleBuilder.java
Labels: 백엔드, 🎵 feat, 🍰 refactor

#30 Feat.[WOOR-143] feat: 커플 변동시 토큰 재발급 기능 구현
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleFacade.java
  src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
  src/test/java/com/musseukpeople/woorimap/couple/presentation/CoupleControllerTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
Labels: 백엔드, 🎵 feat, 🍰 refactor

#31 [WOOR-112] feat: 로그아웃 블랙리스트 등록 기능 구현
  src/main/java/com/musseukpeople/woorimap/auth/application/AuthFacade.java
  src/main/java/com/musseukpeople/woorimap/auth/application/BlackListService.java
  src/main/java/com/musseukpeople/woorimap/auth/application/JwtProvider.java
  src/main/java/com/musseukpeople/woorimap/auth/application/RefreshTokenService.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/BlackList.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/BlackListRepository.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/RefreshToken.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/RefreshTokenRepository.java
  src/main/java/com/musseukpeople/woorimap/auth/domain/login/LoginMember.java
  src/main/java/com/musseukpeople/woorimap/auth/infrastructure/JwtTokenProvider.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthController.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthInterceptor.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/fake/FakeAuthController.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/resolver/AuthArgumentResolver.java
  src/main/java/com/musseukpeople/woorimap/common/config/WebConfig.java
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/test/java/com/musseukpeople/woorimap/auth/acceptance/AuthControllerTest.java
  src/test/java/com/musseukpeople/woorimap/auth/application/AuthFacadeTest.java
  src/test/java/com/musseukpeople/woorimap/auth/application/BlackListServiceTest.java
  src/test/java/com/musseukpeople/woorimap/auth/infrastructure/JwtTokenProviderTest.java
  src/test/java/com/musseukpeople/woorimap/auth/presentation/AuthInterceptorTest.java
  src/test/java/com/musseukpeople/woorimap/util/DatabaseCleanup.java
Labels: 🎵 feat, 🍰 refactor

#35 [WOOR-73] feat: 커플 조회 API 구현
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleFacade.java
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleService.java
  src/main/java/com/musseukpeople/woorimap/couple/application/dto/response/CoupleMemeberResponse.java
  src/main/java/com/musseukpeople/woorimap/couple/application/dto/response/CoupleResponse.java
  src/main/java/com/musseukpeople/woorimap/couple/application/dto/response/InviteCodeResponse.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/Couple.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/vo/CoupleMembers.java
  src/main/java/com/musseukpeople/woorimap/couple/exception/AlreadyCoupleException.java
  src/main/java/com/musseukpeople/woorimap/couple/exception/MappingCoupleMemberException.java
  src/main/java/com/musseukpeople/woorimap/couple/infrastructure/CoupleQueryRepository.java
  src/main/java/com/musseukpeople/woorimap/couple/infrastructure/CoupleQueryRepositoryImpl.java
  src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
  src/main/java/com/musseukpeople/woorimap/member/application/MemberService.java
  src/main/java/com/musseukpeople/woorimap/member/domain/Member.java
  src/main/java/com/musseukpeople/woorimap/member/domain/MemberRepository.java
  src/test/java/com/musseukpeople/woorimap/couple/application/CoupleServiceTest.java
  src/test/java/com/musseukpeople/woorimap/couple/presentation/CoupleControllerTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
Labels: 백엔드, 🎵 feat

#33 [WOOR-55] feat: 회원 정보 조회 API 구현
  src/main/java/com/musseukpeople/woorimap/member/application/MemberService.java
  src/main/java/com/musseukpeople/woorimap/member/application/dto/response/MemberResponse.java
  src/main/java/com/musseukpeople/woorimap/member/domain/MemberRepository.java
  src/main/java/com/musseukpeople/woorimap/member/domain/vo/Password.java
  src/main/java/com/musseukpeople/woorimap/member/presentation/MemberController.java
  src/main/resources/application-test.yml
  src/test/java/com/musseukpeople/woorimap/member/acceptance/MemberAcceptanceTest.java
  src/test/java/com/musseukpeople/woorimap/member/application/MemberServiceTest.java
  src/test/java/com/musseukpeople/woorimap/member/domain/MemberRepositoryTest.java
  src/test/java/com/musseukpeople/woorimap/util/fixture/TMemberBuilder.java
Labels: 🎵 feat

#37 [WOOR-166] fix: 중복 생성된 메서드 삭제
  src/main/java/com/musseukpeople/woorimap/member/application/MemberService.java
  src/main/java/com/musseukpeople/woorimap/member/domain/MemberRepository.java
Labels: 🐛 bug

#36 [WOOR-56] feat: 회원 정보 수정 API 구현
  build.gradle
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorResponse.java
  src/main/java/com/musseukpeople/woorimap/common/validator/ImageUrl.java
  src/main/java/com/musseukpeople/woorimap/common/validator/ImageUrlValidator.java
  src/main/java/com/musseukpeople/woorimap/common/validator/ImageUtil.java
  src/main/java/com/musseukpeople/woorimap/member/application/MemberService.java
  src/main/java/com/musseukpeople/woorimap/member/application/dto/request/EditProfileRequest.java
  src/main/java/com/musseukpeople/woorimap/member/application/dto/response/ProfileResponse.java
  src/main/java/com/musseukpeople/woorimap/member/domain/Member.java
  src/main/java/com/musseukpeople/woorimap/member/presentation/MemberController.java
  src/test/java/com/musseukpeople/woorimap/common/validator/ImageUtilTest.java
  src/test/java/com/musseukpeople/woorimap/member/acceptance/MemberAcceptanceTest.java
  src/test/java/com/musseukpeople/woorimap/member/application/MemberServiceTest.java
Labels: 🎵 feat

#38 [WOOR-72] feat: 커플 수정 API 구현
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleFacade.java
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleService.java
  src/main/java/com/musseukpeople/woorimap/couple/application/dto/request/EditCoupleRequest.java
  src/main/java/com/musseukpeople/woorimap/couple/application/dto/response/CoupleEditResponse.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/Couple.java
  src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
  src/test/java/com/musseukpeople/woorimap/couple/application/CoupleServiceTest.java
  src/test/java/com/musseukpeople/woorimap/couple/presentation/CoupleControllerTest.java
Labels: 백엔드, 🎵 feat

#40 [WOOR-168] refactor: 회원 프로필 조회시 자신의 정보만 변경하도록 변경
  src/main/java/com/musseukpeople/woorimap/member/application/MemberService.java
  src/main/java/com/musseukpeople/woorimap/member/application/dto/response/MemberResponse.java
  src/test/java/com/musseukpeople/woorimap/member/acceptance/MemberAcceptanceTest.java
  src/test/java/com/musseukpeople/woorimap/member/application/MemberServiceTest.java
Labels: 🍰 refactor

#32 [WOOR-37] feat: 게시글 생성 API 구현
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleService.java
  src/main/java/com/musseukpeople/woorimap/post/application/PostFacade.java
  src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
  src/main/java/com/musseukpeople/woorimap/post/application/dto/CreatePostRequest.java
  src/main/java/com/musseukpeople/woorimap/post/domain/Post.java
  src/main/java/com/musseukpeople/woorimap/post/domain/PostImage.java
  src/main/java/com/musseukpeople/woorimap/post/domain/PostRepository.java
  src/main/java/com/musseukpeople/woorimap/post/domain/PostTag.java
  src/main/java/com/musseukpeople/woorimap/post/domain/vo/GPSCoordinates.java
  src/main/java/com/musseukpeople/woorimap/post/exception/NotFoundPostException.java
  src/main/java/com/musseukpeople/woorimap/post/exception/PostException.java
  src/main/java/com/musseukpeople/woorimap/post/presentation/PostController.java
  src/main/java/com/musseukpeople/woorimap/tag/application/TagService.java
  src/main/java/com/musseukpeople/woorimap/tag/application/dto/TagRequest.java
  src/main/java/com/musseukpeople/woorimap/tag/domain/Tag.java
  src/main/java/com/musseukpeople/woorimap/tag/domain/TagRepository.java
  src/main/java/com/musseukpeople/woorimap/tag/infrastructure/QueryTagRepository.java
  src/main/java/com/musseukpeople/woorimap/tag/infrastructure/QueryTagRepositoryImpl.java
  src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
  src/test/java/com/musseukpeople/woorimap/post/presentation/PostControllerTest.java
Labels: 백엔드, 🎵 feat

#41 [WOOR-169] refactor: 로그인, 회원 정보 확인 정보를 통일하도록 변경
  src/main/java/com/musseukpeople/woorimap/auth/application/dto/response/LoginMemberResponse.java
  src/main/java/com/musseukpeople/woorimap/member/application/dto/response/MemberResponse.java
Labels: 🍰 refactor

#42 [WOOR-173] fix: 테스트 메서드 수정
  src/test/java/com/musseukpeople/woorimap/auth/acceptance/AuthControllerTest.java
  src/test/java/com/musseukpeople/woorimap/member/acceptance/MemberAcceptanceTest.java
Labels: 🐛 bug

#39 [WOOR-74] feat: 커플 확인 API 구현
  src/main/java/com/musseukpeople/woorimap/couple/application/CoupleFacade.java
  src/main/java/com/musseukpeople/woorimap/couple/application/dto/response/CoupleCheckResponse.java
  src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
  src/test/java/com/musseukpeople/woorimap/couple/application/CoupleFacadeTest.java
  src/test/java/com/musseukpeople/woorimap/couple/presentation/CoupleControllerTest.java
Labels: 백엔드, 🎵 feat

#45 [WOOR-181] fix: 블랙리스트 TTL 설정 현재 시간 기준으로 설정하도록 변경
  src/main/java/com/musseukpeople/woorimap/auth/application/AuthFacade.java
Labels: 🐛 bug

#34 [Woor-121] feat: 이미지 업로드 API 구현
  build.gradle
  src/main/java/com/musseukpeople/woorimap/common/config/AwsConfig.java
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/common/exception/GlobalExceptionHandler.java
  src/main/java/com/musseukpeople/woorimap/image/application/ImageService.java
  src/main/java/com/musseukpeople/woorimap/image/application/S3ImageService.java
  src/main/java/com/musseukpeople/woorimap/image/domain/FileType.java
  src/main/java/com/musseukpeople/woorimap/image/domain/S3Image.java
  src/main/java/com/musseukpeople/woorimap/image/exception/ConvertFileFailedException.java
  src/main/java/com/musseukpeople/woorimap/image/exception/FileException.java
  src/main/java/com/musseukpeople/woorimap/image/exception/NotSupportImageException.java
  src/main/java/com/musseukpeople/woorimap/image/presentation/ImageController.java
  src/main/java/com/musseukpeople/woorimap/image/util/FileUtils.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/musseukpeople/woorimap/common/config/S3MockConfig.java
  src/test/java/com/musseukpeople/woorimap/image/application/S3ImageServiceTest.java
Labels: 🎵 feat

#46 [WOOR-179] feat: 태그 조회 API 구현
  src/main/java/com/musseukpeople/woorimap/common/config/redis/RedisCachingConfig.java
  src/main/java/com/musseukpeople/woorimap/post/application/dto/CreatePostRequest.java
  src/main/java/com/musseukpeople/woorimap/tag/application/TagService.java
  src/main/java/com/musseukpeople/woorimap/tag/application/dto/request/TagRequest.java
  src/main/java/com/musseukpeople/woorimap/tag/application/dto/response/TagResponse.java
  src/main/java/com/musseukpeople/woorimap/tag/domain/TagRepository.java
  src/main/java/com/musseukpeople/woorimap/tag/infrastructure/QueryTagRepository.java
  src/main/java/com/musseukpeople/woorimap/tag/infrastructure/QueryTagRepositoryImpl.java
  src/main/java/com/musseukpeople/woorimap/tag/presentation/TagController.java
  src/test/java/com/musseukpeople/woorimap/post/application/PostFacadeTest.java
  src/test/java/com/musseukpeople/woorimap/post/presentation/PostControllerTest.java
  src/test/java/com/musseukpeople/woorimap/tag/application/TagServiceTest.java
  src/test/java/com/musseukpeople/woorimap/tag/presentation/TagControllerTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
Labels: 🎵 feat

#50 [WOOR-189] fix: 버그로 인한 sonarcloud 중지
  .github/workflows/ci-build.yml
  build.gradle
Labels: 🐛 bug

#47 [WOOR-65] feat: 게시글 수정 API 구현
  src/main/java/com/musseukpeople/woorimap/post/application/PostFacade.java
  src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
  src/main/java/com/musseukpeople/woorimap/post/application/dto/EditPostRequest.java
  src/main/java/com/musseukpeople/woorimap/post/domain/Post.java
  src/main/java/com/musseukpeople/woorimap/post/domain/image/PostImages.java
  src/main/java/com/musseukpeople/woorimap/post/domain/tag/PostTags.java
  src/main/java/com/musseukpeople/woorimap/post/presentation/PostController.java
  src/test/java/com/musseukpeople/woorimap/post/application/PostFacadeTest.java
  src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
  src/test/java/com/musseukpeople/woorimap/post/presentation/PostControllerTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
Labels: 🎵 feat

#51 [WOOR-192] chore: CORS origin 추가
  src/main/java/com/musseukpeople/woorimap/common/config/WebConfig.java
Labels: 🔨 chore

#55 [WOOR-63] feat : 게시물 단건 조회 API 구현
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/couple/domain/Couple.java
  src/main/java/com/musseukpeople/woorimap/post/application/PostFacade.java
  src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
  src/main/java/com/musseukpeople/woorimap/post/application/dto/request/CreatePostRequest.java
  src/main/java/com/musseukpeople/woorimap/post/application/dto/request/EditPostRequest.java
  src/main/java/com/musseukpeople/woorimap/post/application/dto/response/PostResponse.java
  src/main/java/com/musseukpeople/woorimap/post/domain/Post.java
  src/main/java/com/musseukpeople/woorimap/post/domain/PostRepository.java
  src/main/java/com/musseukpeople/woorimap/post/domain/image/PostImages.java
  src/main/java/com/musseukpeople/woorimap/post/domain/tag/PostTag.java
  src/main/java/com/musseukpeople/woorimap/post/domain/tag/PostTags.java
  src/main/java/com/musseukpeople/woorimap/post/exception/PostNotBelongToCoupleException.java
  src/main/java/com/musseukpeople/woorimap/post/presentation/PostController.java
  src/main/java/com/musseukpeople/woorimap/tag/application/dto/response/PostTagResponse.java
  src/main/resources/application-test.yml
  src/test/java/com/musseukpeople/woorimap/post/application/PostFacadeTest.java
  src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
  src/test/java/com/musseukpeople/woorimap/post/presentation/PostControllerTest.java
  src/test/java/com/musseukpeople/woorimap/tag/presentation/TagControllerTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
Labels: 🎵 feat

#57 [WOOR-222] fix: post 생성 시 태그와 이미지 validation 추가
  src/main/java/com/musseukpeople/woorimap/post/application/dto/request/CreatePostRequest.java
  src/main/java/com/musseukpeople/woorimap/post/application/dto/request/EditPostRequest.java
  src/main/java/com/musseukpeople/woorimap/post/domain/image/PostImages.java
  src/main/java/com/musseukpeople/woorimap/post/domain/tag/PostTags.java
  src/test/java/com/musseukpeople/woorimap/post/domain/PostTest.java
Labels: 🍰 refactor

#54 [WOOR-66] feat: 게시글 삭제 API
  src/main/java/com/musseukpeople/woorimap/post/application/PostFacade.java
  src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
  src/main/java/com/musseukpeople/woorimap/post/presentation/PostController.java
  src/test/java/com/musseukpeople/woorimap/post/application/PostFacadeTest.java
  src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
  src/test/java/com/musseukpeople/woorimap/post/presentation/PostControllerTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
Labels: 🎵 feat

#52 [WOOR-61] feat: 게시글 다건 조회 API 구현
  src/main/java/com/musseukpeople/woorimap/post/application/PostFacade.java
  src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
  src/main/java/com/musseukpeople/woorimap/post/application/dto/request/PostFilterCondition.java
  src/main/java/com/musseukpeople/woorimap/post/application/dto/response/PostSearchResponse.java
  src/main/java/com/musseukpeople/woorimap/post/domain/PostRepository.java
  src/main/java/com/musseukpeople/woorimap/post/infrastructure/PostQueryRepository.java
  src/main/java/com/musseukpeople/woorimap/post/infrastructure/PostQueryRepositoryImpl.java
  src/main/java/com/musseukpeople/woorimap/post/presentation/PostController.java
  src/main/java/com/musseukpeople/woorimap/tag/application/TagService.java
  src/main/java/com/musseukpeople/woorimap/tag/application/dto/response/TagResponse.java
  src/main/resources/application-test.yml
  src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
  src/test/java/com/musseukpeople/woorimap/post/infrastructure/PostQueryRepositoryTest.java
  src/test/java/com/musseukpeople/woorimap/post/presentation/PostControllerTest.java
Labels: 🎵 feat

#58 [WOOR-198] chore: 운영 배포를 위한 프로파일 설정
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthController.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthInterceptor.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/fake/FakeAuthController.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/resolver/AuthArgumentResolver.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/resolver/JwtTokenArgumentResolver.java
  src/main/java/com/musseukpeople/woorimap/common/util/AuthorizationExtractor.java
  src/main/java/com/musseukpeople/woorimap/common/util/CookieUtil.java
  src/main/java/com/musseukpeople/woorimap/common/util/FileUtil.java
  src/main/java/com/musseukpeople/woorimap/common/util/ImageUtil.java
  src/main/java/com/musseukpeople/woorimap/common/validator/ImageUrlValidator.java
  src/main/java/com/musseukpeople/woorimap/image/application/S3ImageService.java
  src/main/resources/appender/file-db-appender.xml
  src/main/resources/appender/file-error-appender.xml
  src/main/resources/appender/file-info-appender.xml
  src/main/resources/appender/file-warn-appender.xml
  src/main/resources/appender/properties/default-properties.xml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/musseukpeople/woorimap/common/util/AuthorizationExtractorTest.java
  src/test/java/com/musseukpeople/woorimap/common/util/ImageUtilTest.java
Labels: 🔨 chore

#60 [WOOR-225] fix: docker timeout 문제 해결
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
Labels: 🐛 bug

#61 [WOOR-226] fix: 운영 서버 배포 문제 해결로 인한 hoxfix 커밋 추가
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
Labels: 🐛 bug, 배포

#63 [WOOR-251] fix: 이미지 중복 제거 못하는 문제 해결
  src/main/java/com/musseukpeople/woorimap/post/domain/PostRepository.java
  src/test/java/com/musseukpeople/woorimap/common/util/ImageUtilTest.java
Labels: 🐛 bug

#62 [WOOR-216] feat: 게시물 생성, 수정 시 이벤트 발행 기능 구현
  .gitignore
  src/main/java/com/musseukpeople/woorimap/common/config/AsyncConfig.java
  src/main/java/com/musseukpeople/woorimap/common/config/redis/RedisConfig.java
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/common/util/LocationUriUtil.java
  src/main/java/com/musseukpeople/woorimap/event/application/EventService.java
  src/main/java/com/musseukpeople/woorimap/event/application/Publisher.java
  src/main/java/com/musseukpeople/woorimap/event/domain/PostEvent.java
  src/main/java/com/musseukpeople/woorimap/event/infrastructure/RedisPublisher.java
  src/main/java/com/musseukpeople/woorimap/notification/application/RedisMessageSubscriber.java
  src/main/java/com/musseukpeople/woorimap/notification/presentation/fake/FakeNotificationController.java
  src/main/java/com/musseukpeople/woorimap/post/application/PostFacade.java
  src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
  src/main/java/com/musseukpeople/woorimap/post/presentation/PostController.java
  src/test/java/com/musseukpeople/woorimap/event/application/EventServiceTest.java
  src/test/java/com/musseukpeople/woorimap/notification/application/RedisMessageSubscriberTest.java
  src/test/java/com/musseukpeople/woorimap/post/application/PostFacadeTest.java
  src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
Labels: 🎵 feat

#64 [WOOR-236] feat: 알림 구독 API 구현
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthInterceptor.java
  src/main/java/com/musseukpeople/woorimap/common/config/WebConfig.java
  src/main/java/com/musseukpeople/woorimap/notification/application/NotificationService.java
  src/main/java/com/musseukpeople/woorimap/notification/domain/EmitterRepository.java
  src/main/java/com/musseukpeople/woorimap/notification/infrastructure/MemoryEmitterRepository.java
  src/main/java/com/musseukpeople/woorimap/notification/presentation/NotificationController.java
  src/main/java/com/musseukpeople/woorimap/notification/presentation/fake/FakeNotificationController.java
  src/main/java/com/musseukpeople/woorimap/notification/presentation/resolver/AuthNotificationArgumentResolver.java
  src/main/java/com/musseukpeople/woorimap/notification/presentation/resolver/LoginForNoti.java
  src/main/java/com/musseukpeople/woorimap/notification/presentation/resolver/LoginRequiredForNoti.java
  src/test/java/com/musseukpeople/woorimap/notification/application/NotificationServiceTest.java
  src/test/java/com/musseukpeople/woorimap/notification/domain/EmitterRepositoryTest.java
  src/test/java/com/musseukpeople/woorimap/notification/presentation/NotificationControllerTest.java
Labels: 🎵 feat

#66 [WOOR-263] chore: sonarcloud 재설정
  .github/workflows/ci-build.yml
  build.gradle
Labels: 🔨 chore

#65 [WOOR-250] feat: 발행된 이벤트 전달 기능 구현
  src/main/java/com/musseukpeople/woorimap/auth/application/AuthFacade.java
  src/main/java/com/musseukpeople/woorimap/common/config/redis/RedisConfig.java
  src/main/java/com/musseukpeople/woorimap/event/application/EventListener.java
  src/main/java/com/musseukpeople/woorimap/event/infrastructure/RedisPublisher.java
  src/main/java/com/musseukpeople/woorimap/notification/application/NotificationService.java
  src/main/java/com/musseukpeople/woorimap/notification/application/dto/response/NotificationResponse.java
  src/main/java/com/musseukpeople/woorimap/notification/application/message/RedisMessageSubscriber.java
  src/main/java/com/musseukpeople/woorimap/notification/domain/EmitterRepository.java
  src/main/java/com/musseukpeople/woorimap/notification/domain/Notification.java
  src/main/java/com/musseukpeople/woorimap/notification/domain/NotificationRepository.java
  src/main/java/com/musseukpeople/woorimap/notification/infrastructure/EmitterRepository.java
  src/main/java/com/musseukpeople/woorimap/notification/infrastructure/MemoryEmitterRepository.java
  src/main/resources/db/migration/V4__add_notification.sql
  src/test/java/com/musseukpeople/woorimap/event/application/EventListenerTest.java
  src/test/java/com/musseukpeople/woorimap/notification/application/NotificationServiceTest.java
  src/test/java/com/musseukpeople/woorimap/notification/application/message/RedisMessageSubscriberTest.java
  src/test/java/com/musseukpeople/woorimap/notification/domain/EmitterRepositoryTest.java
  src/test/java/com/musseukpeople/woorimap/notification/domain/NotificationTest.java
  src/test/java/com/musseukpeople/woorimap/notification/infrastructure/EmitterRepositoryTest.java
Labels: 🎵 feat

#67 [WOOR-264] fix: 커플 해제시 토큰 못받는 버그 해결
  src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
  src/main/resources/appender/access/file-access-appender.xml
  src/test/java/com/musseukpeople/woorimap/couple/presentation/CoupleControllerTest.java
Labels: 백엔드, 🐛 bug

#68 [WOOR-260] feat: 알림 읽음 처리 API 구현
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/notification/application/NotificationService.java
  src/main/java/com/musseukpeople/woorimap/notification/exception/NotFoundNotificationException.java
  src/main/java/com/musseukpeople/woorimap/notification/exception/NotificationException.java
  src/main/java/com/musseukpeople/woorimap/notification/presentation/NotificationController.java
  src/test/java/com/musseukpeople/woorimap/notification/application/NotificationServiceTest.java
  src/test/java/com/musseukpeople/woorimap/notification/presentation/NotificationControllerTest.java
  src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
Labels: 🎵 feat

#69 [WOO-249] feat: 읽지 않은 알림 조회 API 구현
  src/main/java/com/musseukpeople/woorimap/notification/application/NotificationService.java
  src/main/java/com/musseukpeople/woorimap/notification/domain/NotificationRepository.java
  src/main/java/com/musseukpeople/woorimap/notification/presentation/NotificationController.java
  src/main/resources/db/migration/V5__add_foreign_key_to_notification.sql
  src/test/java/com/musseukpeople/woorimap/notification/application/NotificationServiceTest.java
  src/test/java/com/musseukpeople/woorimap/notification/presentation/NotificationControllerTest.java
Labels: 🎵 feat

#73 [WOOR-274] feat: 다중 이미지 업로드 비동기 처리 구현
  .github/workflows/ci-build.yml
  src/main/java/com/musseukpeople/woorimap/image/application/S3ImageService.java
Labels: image

#71 [WOOR-233] refactor: 알림 응답시 타입도 같이 보내도록 리팩토링
  build.gradle
  src/main/java/com/musseukpeople/woorimap/event/domain/PostEvent.java
  src/main/java/com/musseukpeople/woorimap/notification/application/NotificationService.java
  src/main/java/com/musseukpeople/woorimap/notification/application/dto/response/NotificationResponse.java
  src/main/java/com/musseukpeople/woorimap/notification/domain/Notification.java
  src/main/java/com/musseukpeople/woorimap/post/application/PostFacade.java
  src/main/resources/db/migration/V6__delete_foreign_key_to_notification.sql
  src/main/resources/db/migration/V7__change_senderId_colum_in_notification.sql
  src/main/resources/db/migration/V8__add_index_to_notification.sql
  src/test/java/com/musseukpeople/woorimap/event/application/EventListenerTest.java
  src/test/java/com/musseukpeople/woorimap/notification/application/NotificationServiceTest.java
  src/test/java/com/musseukpeople/woorimap/notification/application/message/RedisMessageSubscriberTest.java
  src/test/java/com/musseukpeople/woorimap/notification/domain/NotificationTest.java
  src/test/java/com/musseukpeople/woorimap/notification/infrastructure/EmitterRepositoryTest.java
  src/test/java/com/musseukpeople/woorimap/notification/presentation/NotificationControllerTest.java
Labels: 🍰 refactor

#74 [WOOR-282] feat: 비동기 처리 시 커스텀 스레드풀 사용하도록 수정
  src/main/java/com/musseukpeople/woorimap/common/config/AsyncConfig.java
  src/main/java/com/musseukpeople/woorimap/image/application/S3ImageService.java
Labels: image

#75 [WOOR-230] feat: 커플 상태 변경 시 토큰 재발급 API 구현
  src/main/java/com/musseukpeople/woorimap/auth/aop/LoginMemberVerifier.java
  src/main/java/com/musseukpeople/woorimap/auth/application/AuthFacade.java
  src/main/java/com/musseukpeople/woorimap/auth/application/JwtProvider.java
  src/main/java/com/musseukpeople/woorimap/auth/exception/InvalidTokenRequestException.java
  src/main/java/com/musseukpeople/woorimap/auth/exception/MemberAccessDeniedException.java
  src/main/java/com/musseukpeople/woorimap/auth/infrastructure/JwtTokenProvider.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthController.java
  src/main/java/com/musseukpeople/woorimap/auth/presentation/resolver/AuthArgumentResolver.java
  src/main/java/com/musseukpeople/woorimap/common/exception/ErrorCode.java
  src/main/java/com/musseukpeople/woorimap/event/domain/PostEvent.java
  src/main/java/com/musseukpeople/woorimap/notification/application/NotificationService.java
  src/main/java/com/musseukpeople/woorimap/notification/application/dto/response/NotificationResponse.java
  src/main/java/com/musseukpeople/woorimap/notification/domain/NotificationRepository.java
  src/main/java/com/musseukpeople/woorimap/notification/presentation/resolver/AuthNotificationArgumentResolver.java
  src/main/java/com/musseukpeople/woorimap/post/application/PostFacade.java
  src/test/java/com/musseukpeople/woorimap/auth/acceptance/AuthControllerTest.java
  src/test/java/com/musseukpeople/woorimap/auth/application/AuthFacadeTest.java
  src/test/java/com/musseukpeople/woorimap/auth/infrastructure/JwtTokenProviderTest.java
  src/test/java/com/musseukpeople/woorimap/util/fixture/TCoupleBuilder.java
Labels: 🎵 feat

#72 [WOOR-277] fix: 커플 해제시 외래키 문제로 인한 삭제 버그 해결
  src/main/java/com/musseukpeople/woorimap/couple/domain/Couple.java
  src/main/java/com/musseukpeople/woorimap/post/domain/Post.java
  src/main/java/com/musseukpeople/woorimap/tag/domain/Tag.java
  src/test/java/com/musseukpeople/woorimap/couple/presentation/CoupleControllerTest.java
  src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
  src/test/java/com/musseukpeople/woorimap/post/domain/PostTest.java
Labels: 백엔드, 🐛 bug

#77 [WOOR-321] refactor: core 모듈에서 분리된 알림 모듈 제거
  woorimap-core/src/main/java/com/musseukpeople/woorimap/auth/exception/MemberAccessDeniedExcpetion.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/auth/presentation/AuthInterceptor.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/common/config/WebConfig.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/common/config/redis/RedisConfig.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/application/NotificationService.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/application/dto/response/NotificationResponse.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/application/message/RedisMessageSubscriber.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/domain/Notification.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/domain/NotificationRepository.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/exception/NotFoundNotificationException.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/exception/NotificationException.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/infrastructure/EmitterRepository.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/infrastructure/MemoryEmitterRepository.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/presentation/NotificationController.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/presentation/resolver/AuthNotificationArgumentResolver.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/presentation/resolver/LoginForNoti.java
  woorimap-core/src/main/java/com/musseukpeople/woorimap/notification/presentation/resolver/LoginRequiredForNoti.java
  woorimap-core/src/test/java/com/musseukpeople/woorimap/notification/application/NotificationServiceTest.java
  woorimap-core/src/test/java/com/musseukpeople/woorimap/notification/application/message/RedisMessageSubscriberTest.java
  woorimap-core/src/test/java/com/musseukpeople/woorimap/notification/domain/NotificationTest.java
  woorimap-core/src/test/java/com/musseukpeople/woorimap/notification/infrastructure/EmitterRepositoryTest.java
  woorimap-core/src/test/java/com/musseukpeople/woorimap/notification/presentation/NotificationControllerTest.java
  woorimap-core/src/test/java/com/musseukpeople/woorimap/util/AcceptanceTest.java
  woorimap-core/src/test/java/com/musseukpeople/woorimap/util/IntegrationTest.java
  woorimap-notification/src/main/java/com/musseukpeople/woorimapnotification/notification/application/EmitterService.java
Labels: core, notification
